version: '3.7'

services:
  maven:
    image: lava:latest
    container_name: "maven"
    ports:
    - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    # volumes:
    #   - ./maven-data:/app/src/main
    networks:
     - mynet
  mysql:
    image: mysql:5.7
    container_name: "bazka"
    # command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: lavagna
        MYSQL_USER: app 
        MYSQL_PASSWORD: pass
    ports:
    - 3306:3306
    volumes:
      - /db:/var/lib/mysql
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:3306"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
     - mynet
  nginx:
    image: nginx:1.23.1
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
     - ./conf/nginx.conf:/etc/nginx/nginx.conf
    #  -  ./nginx-data:/usr/share/nginx/html
     - ./maven-data/app/src/main/webapp:/usr/share/nginx/html
     - ./maven-data/app/src/main/webapp/setup/index.html:/usr/share/nginx/html/index.html
    networks:
     - mynet
    depends_on:
      - maven
volumes:
  db:
    driver: local
networks:
  mynet:
    name: mynet